name: build

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build
        run: deno task build

      - name: Set git identity
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to repo
        shell: bash
        run: |
          git add .
          git commit -m "ci: update script"
          for attempt in {1..3}; do
            git push && break || git pull --rebase
          done
