name: build

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Set APP_VERSION
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build
        run: deno task build

      - name: Configure Git
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to repo
        shell: bash
        run: |
          git add .
          git commit -m "ci: update versions in staging.yaml to ${{ env.APP_VERSION }}"
          for attempt in {1..3}; do
            git push && break || git pull --rebase
          done
